#!/usr/bin/env bash
set -Eeuo pipefail
CTX=kubernetes-admin@kubernetes
kubectl --context="$CTX" -n istio-system scale deployment/istio-ingressgateway --replicas=1
kubectl --context="$CTX" -n istio-system scale deployment/istiod --replicas=1
kubectl --context="$CTX" -n mariadb-operator scale deployment/mariadb-operator --replicas=1
kubectl --context="$CTX" -n mariadb-operator scale deployment/mariadb-operator-cert-controller --replicas=1
kubectl --context="$CTX" -n mariadb-operator scale deployment/mariadb-operator-webhook --replicas=1
kubectl --context="$CTX" -n nonrtric scale deployment/a1-sim-osc-0 --replicas=1
kubectl --context="$CTX" -n nonrtric scale deployment/a1-sim-osc-1 --replicas=1
kubectl --context="$CTX" -n nonrtric scale deployment/a1-sim-std-0 --replicas=1
kubectl --context="$CTX" -n nonrtric scale deployment/a1-sim-std-1 --replicas=1
kubectl --context="$CTX" -n nonrtric scale deployment/a1-sim-std2-0 --replicas=1
kubectl --context="$CTX" -n nonrtric scale deployment/a1-sim-std2-1 --replicas=1
kubectl --context="$CTX" -n nonrtric scale deployment/capifcore --replicas=1
kubectl --context="$CTX" -n nonrtric scale deployment/controlpanel --replicas=1
kubectl --context="$CTX" -n nonrtric scale deployment/dmeparticipant --replicas=1
kubectl --context="$CTX" -n nonrtric scale deployment/nonrtricgateway --replicas=1
kubectl --context="$CTX" -n nonrtric scale deployment/oran-nonrtric-kong --replicas=1
kubectl --context="$CTX" -n nonrtric scale deployment/servicemanager --replicas=1
kubectl --context="$CTX" -n nonrtric scale deployment/topology --replicas=1
kubectl --context="$CTX" -n onap scale deployment/onap-cps-core --replicas=1
kubectl --context="$CTX" -n onap scale deployment/onap-cps-temporal --replicas=1
kubectl --context="$CTX" -n onap scale deployment/onap-dcae-ves-collector --replicas=1
kubectl --context="$CTX" -n onap scale deployment/onap-ncmp-dmi-plugin --replicas=1
kubectl --context="$CTX" -n onap scale deployment/onap-policy-apex-pdp --replicas=1
kubectl --context="$CTX" -n onap scale deployment/onap-policy-api --replicas=1
kubectl --context="$CTX" -n onap scale deployment/onap-policy-clamp-ac-a1pms-ppnt --replicas=1
kubectl --context="$CTX" -n onap scale deployment/onap-policy-clamp-ac-http-ppnt --replicas=1
kubectl --context="$CTX" -n onap scale deployment/onap-policy-clamp-ac-k8s-ppnt --replicas=1
kubectl --context="$CTX" -n onap scale deployment/onap-policy-clamp-ac-kserve-ppnt --replicas=1
kubectl --context="$CTX" -n onap scale deployment/onap-policy-clamp-ac-pf-ppnt --replicas=1
kubectl --context="$CTX" -n onap scale deployment/onap-policy-clamp-runtime-acm --replicas=1
kubectl --context="$CTX" -n onap scale deployment/onap-policy-pap --replicas=1
kubectl --context="$CTX" -n onap scale deployment/onap-policy-postgres-primary --replicas=1
kubectl --context="$CTX" -n onap scale deployment/onap-policy-postgres-replica --replicas=1
kubectl --context="$CTX" -n onap scale deployment/onap-postgres-primary --replicas=1
kubectl --context="$CTX" -n onap scale deployment/onap-postgres-replica --replicas=1
kubectl --context="$CTX" -n onap scale deployment/onap-sdnc-ansible-server --replicas=1
kubectl --context="$CTX" -n onap scale deployment/onap-sdnc-web --replicas=1
kubectl --context="$CTX" -n onap scale deployment/onap-strimzi-entity-operator --replicas=1
kubectl --context="$CTX" -n smo scale deployment/bundle-server --replicas=1
kubectl --context="$CTX" -n smo scale deployment/focom-to-teiv-adapter --replicas=1
kubectl --context="$CTX" -n smo scale deployment/keycloak --replicas=1
kubectl --context="$CTX" -n smo scale deployment/keycloak-proxy --replicas=1
kubectl --context="$CTX" -n smo scale deployment/ncmp-to-teiv-adapter --replicas=1
kubectl --context="$CTX" -n smo scale deployment/opa --replicas=1
kubectl --context="$CTX" -n smo scale deployment/redpanda-console --replicas=1
kubectl --context="$CTX" -n smo scale deployment/topology-exposure --replicas=1
kubectl --context="$CTX" -n smo scale deployment/topology-ingestion --replicas=1
kubectl --context="$CTX" -n strimzi-system scale deployment/strimzi-cluster-operator --replicas=1
kubectl --context="$CTX" -n nonrtric scale statefulset/dmaapadapterservice --replicas=1
kubectl --context="$CTX" -n nonrtric scale statefulset/informationservice --replicas=1
kubectl --context="$CTX" -n nonrtric scale statefulset/oran-nonrtric-postgresql --replicas=1
kubectl --context="$CTX" -n nonrtric scale statefulset/policymanagementservice --replicas=1
kubectl --context="$CTX" -n nonrtric scale statefulset/rappmanager --replicas=1
kubectl --context="$CTX" -n onap scale statefulset/mariadb-galera --replicas=1
kubectl --context="$CTX" -n onap scale statefulset/onap-cps-temporal-db --replicas=1
kubectl --context="$CTX" -n onap scale statefulset/onap-sdnc --replicas=1
kubectl --context="$CTX" -n smo scale statefulset/dfc --replicas=1
kubectl --context="$CTX" -n smo scale statefulset/influxdb2 --replicas=1
kubectl --context="$CTX" -n smo scale statefulset/kafka-producer-pm-json2influx --replicas=1
kubectl --context="$CTX" -n smo scale statefulset/kafka-producer-pm-json2kafka --replicas=1
kubectl --context="$CTX" -n smo scale statefulset/kafka-producer-pm-xml2json --replicas=1
kubectl --context="$CTX" -n smo scale statefulset/minio --replicas=1
kubectl --context="$CTX" -n smo scale statefulset/oran-smo-postgresql --replicas=1
kubectl --context="$CTX" -n smo scale statefulset/pm-producer-json2kafka --replicas=1
kubectl --context="$CTX" -n smo scale statefulset/pmlog --replicas=1
