apiVersion: v1
kind: ServiceAccount
metadata: {name: oai-core}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata: {name: smf-pod-reader}
rules:
  - apiGroups: ['']
    resources: [pods]
    verbs: [get, list]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: {name: non-rt-ric-smf-pod-reader}
subjects: [{kind: ServiceAccount, name: non-rt-ric, namespace: non-rt-ric}]
roleRef: {apiGroup: rbac.authorization.k8s.io, kind: Role, name: smf-pod-reader}
