package producer

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"strconv"
	"time"
)

type Config struct {
	Listen, TLSCert, TLSKey, CAFile, StateDir string
	ICSURL, SMFURL, PublicURL                 string
	InfoTypeID, ProducerID, RunID             string
	DNN, SD, SUPI                             string
	SST                                       int
}

type Job struct {
	Owner           string          `json:"owner"`
	LastUpdated     string          `json:"last_updated"`
	ID              string          `json:"info_job_identity"`
	TargetURI       string          `json:"target_uri"`
	Data            json.RawMessage `json:"info_job_data"`
	InformationType string          `json:"info_type_identity"`
}

type Notification struct {
	NotificationID string  `json:"notifId"`
	Events         []Event `json:"eventNotifs"`
}

type Event struct {
	Event      string          `json:"event"`
	Timestamp  string          `json:"timeStamp"`
	SUPI       string          `json:"supi"`
	DNN        string          `json:"dnn"`
	SNSSAI     json.RawMessage `json:"snssai"`
	Customized json.RawMessage `json:"customized_data"`
}

type Normalized struct {
	SchemaVersion    string   `json:"schema_version"`
	RunID            string   `json:"run_id"`
	ObservedAt       string   `json:"observed_at"`
	SMFTimestamp     string   `json:"smf_timestamp"`
	SUPI             string   `json:"supi"`
	SEID             uint64   `json:"seid"`
	SessionEpoch     string   `json:"session_epoch"`
	URRID            *uint64  `json:"urr_id"`
	URSequence       uint64   `json:"ur_seqn"`
	Triggers         []string `json:"triggers"`
	ULBytes          uint64   `json:"ul_bytes"`
	DLBytes          uint64   `json:"dl_bytes"`
	TotalBytes       uint64   `json:"total_bytes"`
	ULPackets        uint64   `json:"ul_packets"`
	DLPackets        uint64   `json:"dl_packets"`
	TotalPackets     uint64   `json:"total_packets"`
	DurationSeconds  uint64   `json:"duration_seconds"`
	DNN              string   `json:"dnn"`
	SNSSAI           SNSSAI   `json:"snssai"`
	EnrichmentSource string   `json:"enrichment_source"`
}

type SNSSAI struct {
	SST int    `json:"sst"`
	SD  string `json:"sd"`
}

func number(m map[string]any, key string) uint64 {
	v, ok := m[key]
	if !ok {
		return 0
	}
	switch n := v.(type) {
	case float64:
		return uint64(n)
	case json.Number:
		u, _ := strconv.ParseUint(n.String(), 10, 64)
		return u
	case string:
		u, _ := strconv.ParseUint(n, 10, 64)
		return u
	}
	return 0
}

func Normalize(e Event, c Config, now time.Time) (Normalized, error) {
	if e.Event != "QOS_MON" {
		return Normalized{}, fmt.Errorf("unsupported event %q", e.Event)
	}
	var u map[string]any
	dec := json.NewDecoder(bytes.NewReader(e.Customized))
	dec.UseNumber()
	if err := dec.Decode(&u); err != nil {
		return Normalized{}, fmt.Errorf("customized_data: %w", err)
	}
	// OAI serializes an EventNotification inside customized_data; its Usage
	// Report member contains the PFCP counters. The direct form is accepted
	// for offline fixtures generated by older lab runs.
	if nested, ok := u["Usage Report"].(map[string]any); ok {
		u = nested
	}
	seid, seq := number(u, "SEID"), number(u, "UR-SEQN")
	if seid == 0 || seq == 0 {
		return Normalized{}, errors.New("customized_data requires positive SEID and UR-SEQN")
	}
	vol, _ := u["Volume"].(map[string]any)
	nop, _ := u["NoP"].(map[string]any)
	triggers := []string{}
	switch t := u["Trigger"].(type) {
	case string:
		if t != "" {
			triggers = append(triggers, t)
		}
	case []any:
		for _, x := range t {
			if s, ok := x.(string); ok {
				triggers = append(triggers, s)
			}
		}
	}
	supi := e.SUPI
	if supi == "" {
		supi = c.SUPI
	}
	if c.SUPI != "" && supi != c.SUPI {
		return Normalized{}, fmt.Errorf("SUPI %q does not match configured UE", supi)
	}
	dnn := e.DNN
	source := "smf-callback"
	if dnn == "" {
		dnn = c.DNN
		source = "lab-config"
	}
	return Normalized{SchemaVersion: "1.1.0", RunID: c.RunID, ObservedAt: now.UTC().Format(time.RFC3339Nano), SMFTimestamp: e.Timestamp, SUPI: supi, SEID: seid, URSequence: seq, Triggers: triggers, ULBytes: number(vol, "Uplink"), DLBytes: number(vol, "Downlink"), TotalBytes: number(vol, "Total"), ULPackets: number(nop, "Uplink"), DLPackets: number(nop, "Downlink"), TotalPackets: number(nop, "Total"), DurationSeconds: number(u, "Duration"), DNN: dnn, SNSSAI: SNSSAI{SST: c.SST, SD: c.SD}, EnrichmentSource: source}, nil
}
