apiVersion: v2
name: oai-lab
version: 0.1.0
type: application
dependencies:
- name: oai-nrf
  version: v2.2.0
  repository: file://../vendor/oai-5g-core/oai-nrf
  condition: oai-nrf.enabled
- name: oai-udr
  version: v2.2.0
  repository: file://../vendor/oai-5g-core/oai-udr
  condition: oai-udr.enabled
- name: oai-udm
  version: v2.2.0
  repository: file://../vendor/oai-5g-core/oai-udm
  condition: oai-udm.enabled
- name: oai-ausf
  version: v2.2.0
  repository: file://../vendor/oai-5g-core/oai-ausf
  condition: oai-ausf.enabled
- name: oai-amf
  version: v2.2.0
  repository: file://../vendor/oai-5g-core/oai-amf
  condition: oai-amf.enabled
- name: oai-smf
  version: v2.2.0
  repository: file://../vendor/oai-5g-core/oai-smf
  condition: oai-smf.enabled
- name: oai-upf
  version: v2.2.0
  repository: file://../vendor/oai-5g-core/oai-upf
  condition: oai-upf.enabled
- name: oai-flexric
  version: 1.0.0
  repository: file://../vendor/oai-5g-ran/oai-flexric
  condition: oai-flexric.enabled
- name: oai-gnb
  version: 2.4.0
  repository: file://../vendor/oai-5g-ran/oai-gnb
  condition: oai-gnb.enabled
- name: oai-nr-ue
  version: 2.4.0
  repository: file://../vendor/oai-5g-ran/oai-nr-ue
  condition: oai-nr-ue.enabled
