global:
  lab:
    toolsImage: oai-lab-tools:r1-1a8c19404f3d
    workloads:
      flexric:
        image: oai-lab-radio:bf98ff282ed25e3f
      gnb:
        image: oai-lab-radio:bf98ff282ed25e3f
      nr-ue:
        image: oai-lab-radio:bf98ff282ed25e3f
      smf:
        image: oai-lab-smf:v2.2.0-lab-e2aa7c54
      upf:
        image: oai-lab-upf:ttl-afdf292e9d3a
